Basic HTML, CSS and JS funcitonality
DavidEspinoG/microverse_capstone_one pull request #1
Opened 2023-02-07 20:18 UTC by DavidEspinoG

- Add Responsive home page and about page
- JS functionality for burger menu in mobile devices
- Add npm run test command for running stylelint and eslint tests 
- Add npm run fix command for fixing stylelint and eslint tests
- Add JS code for create speakers section dynamically

2023-02-07 21:39 UTC, huseyinbiyik requested changes
Hi @DavidEspinoG,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝

## Required Changes ♻️
- Please add the project presentation video as requested on the project requirements:
<img width="1145" alt="Screenshot 2023-02-07 at 11 26 36 PM" src="https://user-images.githubusercontent.com/25887253/217357744-1e53473d-0ab2-45ea-98f8-17999a04ebb8.png">

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 21:39 UTC, huseyinbiyik commented on README.MD
> +- [Live Demo Link(deploy pending)](https://davidespinog.github.io/portfolio/)
Kindly deploy your project from this branch and fix this link. We need to see if your deployment works properly. You can change your deployment branch after you merge the branch to the main 👍

2023-02-07 21:39 UTC, huseyinbiyik commented on about.html
> +    </div>
-Kindly use `<footer>` for wrapping this element instead of div.  The section above can be wrapped with `<section>`element.

- Good job with the alignment 👍  But let's follow the design make logo and text smaller and give some space on the left of them as I marked below.
<img width="414" alt="Screenshot 2023-02-07 at 11 38 50 PM" src="https://user-images.githubusercontent.com/25887253/217361273-8dcb5a77-86f2-4e78-885d-e9dc73ecb05b.png">
<img width="414" alt="Screenshot 2023-02-07 at 11 39 26 PM" src="https://user-images.githubusercontent.com/25887253/217361283-9692c332-ccb8-49f6-919d-8519477457a8.png">

2023-02-07 21:39 UTC, huseyinbiyik commented on styles.css
> +  .license {
Great job with the desktop alignment 👍  But let's make sure the background color matches with the given design.
About Page: It has a dark background.
Home Page: It has a white background.
<img width="836" alt="Screenshot 2023-02-07 at 11 45 26 PM" src="https://user-images.githubusercontent.com/25887253/217362254-f62a4e30-6b1f-495b-a68f-cfe062ea5b93.png">

2023-02-07 21:39 UTC, huseyinbiyik commented on styles.css
> +.speakers__card {
Great job with using display:grid. Let's fix the overlaying issue and we are good here 👍 
<img width="419" alt="Screenshot 2023-02-07 at 11 53 10 PM" src="https://user-images.githubusercontent.com/25887253/217363645-31782a59-1047-4503-a68b-26c9500604c0.png">

2023-02-07 21:39 UTC, huseyinbiyik commented on index.html
>              <div class="program__card">
Great job with using  semantic `<main>` element as wrapper here. Let's change this program cards container as `<article>` to make your HTML more semantic. It is important having an accessible and SEO friendly web pages.

2023-02-07 21:39 UTC, huseyinbiyik commented on profileGenerator.js
> +  const card = document.createElement('div');
Good job creating speakers section dynamically. But kindly use semantic article element instead of div.

2023-02-07 21:39 UTC, huseyinbiyik commented on index.html
> +    <div class="license">
-Kindly use `<footer>` for wrapping this element instead of div. The section above can be wrapped with `<section>` element.

2023-02-07 21:39 UTC, huseyinbiyik commented on index.html
> +            <img class="footer__logo"  src="./img/google-logo.svg" alt="">
Kindly add alt description to each img element in your web pages.

2023-02-07 21:39 UTC, huseyinbiyik commented on profileGenerator.js
> +  const img = document.createElement('img');
Please add alt attribute to each img element on your web pages. It is crucial for accessibility, especially for the people who has visual impairments.

2023-02-08 00:13 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @DavidEspinoG, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Linter set up well and checks pass 🟢
 - GitHub flow followed 👌
 - Commit messages are meaningful and written in imperative tense 📝
 - PR description is descriptive 📝

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 00:13 UTC, leonardodiasb commented on about.html
> +    </footer>
- [ ] Your footer is great, but as the previous code reviewer mentioned, the colors of the footer on the mobile view of both pages should be white for the background and dark for the text and logo. Kindly invert the colors for the mobile view of the about page to match the template.
 - Your design:
 - 
<img width="439" alt="image" src="https://user-images.githubusercontent.com/61919617/217395564-ffc2ce08-d5b0-44ce-89f6-4b892684009e.png">

 - Template:
 - 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/61919617/217395612-367f20a5-3be2-4072-bd76-4b7ee4443a6b.png">

2023-02-08 15:33 UTC, ABDULALI3468 approved these changes
Hi @DavidEspinoG , 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 15:34 UTC, merged